### ISSUE TITLE
Simple record creation?

### ISSUE THREAD

**Issue by rwjack** [ctxis/SnitchDNS#12]
Something else did actually come up :)

I was just wondering if there is a simple way of creating records in a single zone?

Eg. -> I create a `home.lan` zone, and in it have records for 
- snitch : 10.0.0.1
- x : 10.0.0.2
- y : 10.0.0.3
etc...
So when going to snitch.home.lan in my browser it would resolve to 10.0.0.1

Something similar to my Pi-Hole config?
![image](https://user-images.githubusercontent.com/59068073/155727629-68bbd96d-b264-4790-9ad1-64e68d7338bf.png)

I found the snitch config a bit confusing since I'm used to having a query and a response. Here I just see the response? Seems a bit overkill having to create zones for each query and then add A records individually
![image](https://user-images.githubusercontent.com/59068073/155728436-7e80832c-608c-47da-ab05-beb4762f7095.png)

I might understand how basic DNS works, but apparently I'm not a guru, seeing all the options I could configure inside snitch.

**Comment by sadreck** [comment]
Yes, at the moment the way the GUI works is that each (sub)domain is its own zone, and from GUI there isn't a quick and easy way of creating zones as a batch.

You could however batch-import them using a CSV by visiting `/dns/import` - would that work?

**Comment by rwjack** [comment]
I did most of the stuff manually, don't have a lot of records, but it would be nice to have a simple way of migrating to snitch, for future reference.
