### ISSUE TITLE
Feature Request: Restart Daemon Button

### ISSUE THREAD

**Issue by rwjack** [ctxis/SnitchDNS#13]
So this is just a QOL thing, but it was a bit annoying when my entire infrastructure stopped working (since it depends on DNS) after I pressed the stop button :)

![image](https://user-images.githubusercontent.com/59068073/155750821-f9a4d111-1e69-4f77-929a-9b079f8c1675.png)

Would be better if we had a restart button instead.

**Comment by sadreck** [comment]
Yes, I can add a restart button but there would still be a few seconds of the server being down while it's restarting - unless you mean a "live reload"?

**Comment by rwjack** [comment]
Don't think a live reload is necessary, just having a reload button instead of a stop button, or maybe even next to it.

My reasoning was who would ever want to stop their DNS server? If I'd have to stop it, I'd already be in the terminal doing what I need to do, and from there I can stop/start/restart. Though since config changes from the web UI DO REQUIRE a restart, it's weird not having a restart button, rather than having only a stop button.

**Comment by sadreck** [comment]
Yeah, that makes sense - I've added that functionality. Pull the latest and greatest and give it a go.
