### ISSUE TITLE
Docker/Containerd build failed

### ISSUE THREAD

**Issue by ywnsya** [ctxis/SnitchDNS#17]
I try to use containerd to build the docker image
I used ”nerdctl build -t snitchdns .“
Then it failed：
failed to ingest "blobs/sha256/b0cc371e7aa86d19fa79c5287223fb612aa86ef46d18296a8273df198719caa1": failed to read expected number of bytes: unexpected EOF

OS：Centos7.9.2009 
CPU：AMD Ryzen 9 5900X

**Comment by sadreck** [comment]
Apologies for the extra late response, but I can' reproduce this - seems to be working fine on my end. If this is still an issue feel free to reopen this issue.
