### ISSUE TITLE
Install failes with "python setup.py egg_info did not run successfully."

### ISSUE THREAD

**Issue by Dj-Codeman** [ctxis/SnitchDNS#18]
This is my first issue pardon me for missing anything. After installing python and the venv when installing from the requirements.txt I get "python setup.py egg_info did not run successfully." with "The license_file parameter is deprecated, use license_files instead." following in the output.

**Comment by sadreck** [comment]
There's a few prerequisites that you need to install as mentioned at https://github.com/ctxis/SnitchDNS/blob/master/docs/setup/manual.md#packages

```
sudo apt install git python3-pip python3-venv libpq-dev
```

If that doesn't work feel free to re-open this issue - and please include OS and python version!
