### ISSUE TITLE
It is possible to use hostname in A and AAAA record?

### ISSUE THREAD

**Issue by kadogo** [ctxis/SnitchDNS#22]
Hello

I think I know the answer, but I still want to ask in case I missed something.
Based on https://ns1.com/resources/dns-types-records-servers-and-queries I understand that the A record contain hostname and IP.

I guess I can make it work by making a new zone for each domain like `www.example.com` instead of using the zone `example.com` with an A record that will contain the hostname `www` and the ipv4. From my reading, it looks like it's not implemented in twisted, but maybe I understand something wrong.

Thanks for your help.

Cheers

**Comment by sadreck** [comment]
Hi,

The A/AAAA records can only contain IPs, if you want to "redirect" your DNS query to a different domain/zone you would use a `CNAME` record.

For example, check out `www.bbc.co.uk` below:

```
$ dig -t A www.bbc.co.uk @8.8.8.8

; <<>> DiG 9.16.1-Ubuntu <<>> -t A www.bbc.co.uk @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13308
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.bbc.co.uk.			IN	A

;; ANSWER SECTION:
www.bbc.co.uk.		15753	IN	CNAME	www.bbc.co.uk.pri.bbc.co.uk.
www.bbc.co.uk.pri.bbc.co.uk. 300 IN	CNAME	gtm-uk.www.bbc.co.uk.pri.bbc.co.uk.
gtm-uk.www.bbc.co.uk.pri.bbc.co.uk. 300	IN A	212.58.237.129
gtm-uk.www.bbc.co.uk.pri.bbc.co.uk. 300	IN A	212.58.235.129
gtm-uk.www.bbc.co.uk.pri.bbc.co.uk. 300	IN A	212.58.235.1
gtm-uk.www.bbc.co.uk.pri.bbc.co.uk. 300	IN A	212.58.236.1
gtm-uk.www.bbc.co.uk.pri.bbc.co.uk. 300	IN A	212.58.236.129
gtm-uk.www.bbc.co.uk.pri.bbc.co.uk. 300	IN A	212.58.237.1

;; Query time: 23 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Aug 15 19:04:10 BST 2023
;; MSG SIZE  rcvd: 191
```

While we ask for `A` it returns a `CNAME` and then the IPs for it.

Thanks,
Pavel

**Comment by kadogo** [comment]
Hello @sadreck 

Thanks for your fast answer, maybe I didn't explain it clearly but I still think it is a "A" record if I check the bind example from redhat (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/assembly_setting-up-and-configuring-a-bind-dns-server_networking-infrastructure-services)

```
@ IN SOA ns1.example.com. hostmaster.example.com. (
                          2022070601 ; serial number
                          1d         ; refresh period
                          3h         ; retry period
                          3d         ; expire time
                          3h )       ; minimum TTL

                  IN NS   ns1.example.com.
                  IN MX   10 mail.example.com.

www               IN A    192.0.2.30
www               IN AAAA 2001:db8:1::30
ns1               IN A    192.0.2.1
ns1               IN AAAA 2001:db8:1::1
mail              IN A    192.0.2.20
mail              IN AAAA 2001:db8:1::20
```

If my understanding is correct, the bind example is the zone file of `example.com` and we have A record like `mail` that is linked to an IP.

I'm wrong or maybe it's just bind representation?

**Comment by sadreck** [comment]
I believe the `mail` record is for the subdomain `mail.example.com` rather than `example.com`

**Comment by kadogo** [comment]
And for doing that kind of configuration in SnitchDNS I would make a zone "mail.example.com" with an A record `192.0.2.20` ?

**Comment by sadreck** [comment]
Yes, exactly!

**Comment by kadogo** [comment]
Ok thanks, I guess it must be something related to bind, maybe. I didn't find anything related to that in the RFC, only "host address".

Edit:
Hello again @sadreck, do you think it would be possible to make it easier to read, maybe?
I continue to read a bit and I think I understand that the subdomain is not in the A record itself, but that it's also not a new zone.

I think it would be useful to maybe managed that under the hood if it's possible. I would understand if it's a very low priority because it already works, but I think it would be easier to read with 1 main zone that many zones.

**Comment by kadogo** [comment]
Sorry for answering again @sadreck 

I read a bit of the documentation of twisted, and it looks like they use something similar but not with their method if I understood correctly. I'm not so good in python to really understand, but maybe you will understand it better.

https://docs.twisted.org/en/stable/names/howto/names.html

It's mainly about this line

```
    A('example-domain.com', '127.0.0.1'),
```

Thanks again and sorry to disturb you again about that.

Cheers
