### ISSUE TITLE
Does this tool support 0x20 encoding?

### ISSUE THREAD

**Issue by unsocial-bleach** [ctxis/SnitchDNS#9]
When proxying the DNS requests, can this tool send the response using proper [0x20 DNS encoding](https://datatracker.ietf.org/doc/html/draft-vixie-dnsext-dns0x20-00)? Does it do this by default?

I would suggest adding a note about this (whether or not the tool supports it) to the README.

**Comment by sadreck** [comment]
Hi,

As mentioned in the README, SnitchDNS does not implement its own DNS library but is based on [Twisted](https://github.com/twisted/twisted). I had a look at the features/code/tickets and couldn't find any reference to 0x20 DNS Encoding, therefore it's not supported in SnitchDNS either.

Thanks,
Pavel

**Comment by unsocial-bleach** [comment]
What would be required to add support for 0x20 DNS encoding? Also, where are Twisted's issue documented? It appears that they're turned off on GitHub

**Comment by sadreck** [comment]
Twisted's issues are documented here: https://www.twistedmatrix.com/trac/report

If they implement it in the library, then I could make it an option in SnitchDNS.

**Comment by unsocial-bleach** [comment]
Feature requested. See you in a year.

Twisted feature request ticket: https://twistedmatrix.com/trac/ticket/10272
